apiVersion: 1

datasources:
  - name: TravelHub Postgres
    uid: travelhub-postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: false

    url: postgres:5432
    database: travelhub
    user: travelhub

    secureJsonData:
      password: travelhub

    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      timezone: America/Bogota