version: '3.8'

services:  
  busqueda:
    build: ./services/busqueda
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Bogota
    networks:
      - travelhub-net
  inventario:
    build: ./services/inventario
    ports:
      - "5001:5001"
    environment:
      - TZ=America/Bogota
    networks:
      - travelhub-net
  ordenes:
    build: ./services/ordenes
    ports:
      - "5002:5002"
    networks:
      - travelhub-net
  reservas:
    build: ./services/reservas
    ports:
      - "5003:5003"
    environment:
      - TZ=America/Bogota
    networks:
      - travelhub-net
  usuarios:
    build: ./services/usuarios
    ports:
      - "5004:5004"
    environment:
      - TZ=America/Bogota
    networks:
      - travelhub-net

networks:
  travelhub-net:
    driver: bridge